server:
  session-timeout: 1800
  port: 8084
  
spring:
  profiles: 
    active: dev
  application:
    name:web-service-2
    
trace:
  brave:
    name: web-service2-provider
    address: http://127.0.0.1:9411/api/v2/spans
    rate: 1.0
    connectTimeout: 5000
    readTimeout: 5000    
#service version config
service:
  version: 1.0.0
  
#dubbo config
dubbo:
  application:
    id: web-service2-provider
    name: web-service2-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20883
    status: server
  provider:
    timeout: 2000
    filter: tracing
  consumer:
    filter: tracing

#mybatis configuration
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.growithus.**.bean
  
  
rabbitmq:
  queue:
    sms: demo.sms.queue
    push: demo.app.push.queue